import logging
import logzero
from logzero import logger
import pandas as pd
from .peak import PeaksFinder
from BITS.utils import save_pickle


def main():
    args = load_args()



def load_args():
    import argparse
    parser = argparse.ArgumentParser(
        description=(""))

    parser.add_argument(
        "-r",
        "--reads_fname",
        type=str,
        default="reads",
        help=("A file of the raw reads. [reads]"))

    parser.add_argument(
        "-u",
        "--repr_units_fname",
        type=str,
        default="repr_units",
        help=("A file of the representative units generated by dacmaster. [repr_units]"))

    parser.add_argument(
        "-n",
        "--n_core",
        type=int,
        default=1,
        help=("Degree of parallelization. [1]"))

    parser.add_argument(
        "-D",
        "--debug_mode",
        action="store_true",
        default=False,
        help=("Run in debug mode. [False]"))

    args = parser.parse_args()
    if args.debug_mode:
        logzero.loglevel(logging.DEBUG)
        pd.set_option('expand_frame_repr', False)   # show entire dataframe
    else:
        logzero.loglevel(logging.INFO)
    del args.debug_mode

    return args


if __name__ == "__main__":
    main()
